name: Release drafter

# Push events to every tag not containing "/"
on:
  push:
    tags:
      - "*"

jobs:
  draft-a-release:
    name: Draft a release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v2.27.0
        with:
          workflow: sql-odbc-main.yml
          commit: ${{github.sha}}
          workflow_conclusion: success

      - name: Rename and pack artifacts
        run: |
          # replace spaces by dashes in file names
          for i in *-installer/*; do mv "$i" "${i//\ /-}"; done
          tar -cvf artifacts.tar.gz *-installer

      - name: Draft a release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          generate_release_notes: true
          files: artifacts.tar.gz
