name: Release drafter

# Push events to every tag not containing "/"
on:
  push:
    tags:
      - "*"

jobs:
  draft-a-release:
    name: Draft a release
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v2.27.0
        with:
          workflow: sql-odbc-main.yml
          branch: main
          workflow_conclusion: success
          skip_unpack: true

      - name: Draft a release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          generate_release_notes: true
          files: |
            mac64-build.zip
            windows32-installer.zip
            windows64-installer.zip
